<?php
			$optionsArray = array( 'totals' => array( 'RUBRO_ID' => array( 'totalsType' => '' ),
'RUBRO_ID_FK' => array( 'totalsType' => '' ),
'VIGENCIA' => array( 'totalsType' => '' ),
'UEJ' => array( 'totalsType' => '' ),
'RUBRO' => array( 'totalsType' => '' ),
'DESCRIPCION' => array( 'totalsType' => '' ),
'REC' => array( 'totalsType' => '' ),
'FUENTE' => array( 'totalsType' => '' ),
'TIPO' => array( 'totalsType' => '' ),
'TIPO_FUENTE' => array( 'totalsType' => '' ),
'BPIN' => array( 'totalsType' => '' ),
'PRESUPUESTO' => array( 'totalsType' => '' ),
'SALDO' => array( 'totalsType' => '' ),
'Dependencia' => array( 'totalsType' => '' ),
'UsuarioResp' => array( 'totalsType' => '' ),
'CATEGORIA' => array( 'totalsType' => '' ),
'OBJ_GENERAL' => array( 'totalsType' => '' ),
'OBJ_ESPECIFICO' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'VIGENCIA',
'TIPO',
'UEJ',
'RUBRO',
'BPIN',
'REC',
'FUENTE',
'PRESUPUESTO',
'Dependencia',
'DESCRIPCION',
'TIPO_FUENTE',
'CATEGORIA',
'SALDO',
'OBJ_GENERAL' ),
'exportFields' => array( 'VIGENCIA',
'TIPO',
'UEJ',
'RUBRO',
'BPIN',
'REC',
'FUENTE',
'PRESUPUESTO',
'Dependencia',
'DESCRIPCION',
'TIPO_FUENTE',
'CATEGORIA',
'SALDO',
'OBJ_GENERAL' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'VIGENCIA' => array( 'export_field1' ),
'TIPO' => array( 'export_field2' ),
'UEJ' => array( 'export_field3' ),
'RUBRO' => array( 'export_field4' ),
'BPIN' => array( 'export_field5' ),
'REC' => array( 'export_field6' ),
'FUENTE' => array( 'export_field7' ),
'PRESUPUESTO' => array( 'export_field9' ),
'Dependencia' => array( 'export_field10' ),
'DESCRIPCION' => array( 'export_field' ),
'TIPO_FUENTE' => array( 'export_field8' ),
'CATEGORIA' => array( 'export_field11' ),
'SALDO' => array( 'export_field12' ),
'OBJ_GENERAL' => array( 'export_field13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field9',
'export_field10',
'export_field',
'export_field8',
'export_field11',
'export_field12',
'export_field13' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field' => 'grid',
'export_field8' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field9',
'export_field10',
'export_field',
'export_field8',
'export_field11',
'export_field12',
'export_field13' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field9',
'export_field10',
'export_field',
'export_field8',
'export_field11',
'export_field12',
'export_field13' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'VIGENCIA',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'TIPO',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'UEJ',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'RUBRO',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'BPIN',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'REC',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'FUENTE',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'PRESUPUESTO',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Dependencia',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'DESCRIPCION',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'TIPO_FUENTE',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'CATEGORIA',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'SALDO',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'OBJ_GENERAL',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>