<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'CODDPTO',
'CODMUN',
'CODCENTPOBLADO',
'NOMDPTO',
'NOMMUNICIPIO',
'NOMCENTPOBLADO',
'TIPOCENTPOBLADO',
'LON',
'F9',
'LAT',
'DISTRITO',
'TIPOMUN',
'AREAMETRO',
'CENSO' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'CODDPTO' => array( 'import_field' ),
'CODMUN' => array( 'import_field1' ),
'CODCENTPOBLADO' => array( 'import_field2' ),
'NOMDPTO' => array( 'import_field3' ),
'NOMMUNICIPIO' => array( 'import_field4' ),
'NOMCENTPOBLADO' => array( 'import_field5' ),
'TIPOCENTPOBLADO' => array( 'import_field6' ),
'LON' => array( 'import_field7' ),
'F9' => array( 'import_field8' ),
'LAT' => array( 'import_field9' ),
'DISTRITO' => array( 'import_field10' ),
'TIPOMUN' => array( 'import_field11' ),
'AREAMETRO' => array( 'import_field12' ),
'CENSO' => array( 'import_field13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'CODDPTO',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'CODMUN',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'CODCENTPOBLADO',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'NOMDPTO',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'NOMMUNICIPIO',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'NOMCENTPOBLADO',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'TIPOCENTPOBLADO',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'LON',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'F9',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'LAT',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'DISTRITO',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'TIPOMUN',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'AREAMETRO',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'CENSO',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>