<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => true,
'inlineEdit' => false,
'delete' => true,
'updateSelected' => false,
'addInPopup' => true,
'editInPopup' => true,
'viewInPopup' => true,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'master' => array( 'funcionario' => array( 'preview' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'idusrglobal' => array( 'totalsType' => '' ),
'id_fk' => array( 'totalsType' => '' ),
'Username' => array( 'totalsType' => '' ),
'Password' => array( 'totalsType' => '' ),
'usr_email' => array( 'totalsType' => '' ),
'usr_name' => array( 'totalsType' => '' ),
'usr_lname' => array( 'totalsType' => '' ),
'usr_nombresfull' => array( 'totalsType' => '' ),
'usr_personalid' => array( 'totalsType' => '' ),
'usr_inicial' => array( 'totalsType' => '' ),
'usr_sessini' => array( 'totalsType' => '' ),
'usr_image' => array( 'totalsType' => '' ),
'usr_status_nomina' => array( 'totalsType' => '' ),
'usr_status' => array( 'totalsType' => '' ),
'usr_rdnkey' => array( 'totalsType' => '' ),
'usr_type_vinc' => array( 'totalsType' => '' ),
'usr_type_vinculacion' => array( 'totalsType' => '' ),
'usr_status_sol' => array( 'totalsType' => '' ),
'usr_dependencia' => array( 'totalsType' => '' ),
'user_dep' => array( 'totalsType' => '' ),
'usr_entidad' => array( 'totalsType' => '' ),
'usr_not' => array( 'totalsType' => '' ),
'usr_not_msj' => array( 'totalsType' => '' ),
'usr_jefe' => array( 'totalsType' => '' ),
'usr_minequipo_lider' => array( 'totalsType' => '' ),
'usr_minequipo_grupo' => array( 'totalsType' => '' ),
'global_rol_me' => array( 'totalsType' => '' ),
'global_rol_gh' => array( 'totalsType' => '' ),
'global_rol_almacen' => array( 'totalsType' => '' ),
'global_rol_ci' => array( 'totalsType' => '' ),
'global_rol_contratos' => array( 'totalsType' => '' ),
'global_rol_hojar' => array( 'totalsType' => '' ),
'global_rol_inmuebles' => array( 'totalsType' => '' ),
'global_rol_siis' => array( 'totalsType' => '' ),
'global_rol_cpanel' => array( 'totalsType' => '' ),
'global_rol_dashboard' => array( 'totalsType' => '' ),
'global_rol_zf' => array( 'totalsType' => '' ),
'global_rol_sipi' => array( 'totalsType' => '' ),
'global_rol_cej' => array( 'totalsType' => '' ),
'global_rol_jc3' => array( 'totalsType' => '' ),
'global_rol_th' => array( 'totalsType' => '' ),
'global_rol_sid' => array( 'totalsType' => '' ),
'global_rol' => array( 'totalsType' => '' ),
'global_rol_cont' => array( 'totalsType' => '' ),
'globla_rol_ct' => array( 'totalsType' => '' ),
'global_rol_procjur' => array( 'totalsType' => '' ),
'global_rol_comacc' => array( 'totalsType' => '' ),
'global_rol_gestion' => array( 'totalsType' => '' ),
'global_rol_ciudadano' => array( 'totalsType' => '' ),
'global_rol_ciudadano_dep' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'sys_time' => array( 'totalsType' => '' ),
'sys_ntries_usr' => array( 'totalsType' => '' ),
'sys_registrationdate_usr' => array( 'totalsType' => '' ),
'sys_expiration_usr' => array( 'totalsType' => '' ),
'sys_disabledate_usr' => array( 'totalsType' => '' ),
'sys_upd_fecha' => array( 'totalsType' => '' ),
'sys_upd_user' => array( 'totalsType' => '' ),
'sys_upd_time' => array( 'totalsType' => '' ),
'sys_update_info' => array( 'totalsType' => '' ),
'sys_update_family_info' => array( 'totalsType' => '' ),
'usr_update_almacen' => array( 'totalsType' => '' ),
'sys_anio' => array( 'totalsType' => '' ),
'ctrl' => array( 'totalsType' => '' ),
'usr_dep' => array( 'totalsType' => '' ),
'usr_cargo' => array( 'totalsType' => '' ),
'usr_regpago' => array( 'totalsType' => '' ),
'usr_extension' => array( 'totalsType' => '' ),
'usr_piso' => array( 'totalsType' => '' ),
'usr_datebirth' => array( 'totalsType' => '' ),
'ctrl_pedidoalmacen' => array( 'totalsType' => '' ),
'ctrl_contacto' => array( 'totalsType' => '' ),
'usr_emergencia' => array( 'totalsType' => '' ),
'upd_date' => array( 'totalsType' => '' ),
'active' => array( 'totalsType' => '' ),
'groupid' => array( 'totalsType' => '' ),
'habilita_almacen' => array( 'totalsType' => '' ),
'estado_vinculacion_mincit' => array( 'totalsType' => '' ),
'phone' => array( 'totalsType' => '' ),
'phone1' => array( 'totalsType' => '' ),
'usr_directivo' => array( 'totalsType' => '' ),
'usr_dep_sup' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Username',
'usr_email',
'usr_name',
'usr_lname',
'usr_personalid',
'global_rol_almacen',
'global_rol_contratos',
'sys_user',
'sys_date',
'sys_time',
'usr_dep',
'usr_cargo',
'usr_extension',
'usr_datebirth',
'active',
'groupid',
'id_fk',
'phone',
'usr_directivo',
'usr_dep_sup' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'usr_personalid',
'phone1',
'usr_dep_sup',
'usr_directivo',
'phone',
'estado_vinculacion_mincit',
'habilita_almacen',
'upd_date',
'usr_emergencia',
'ctrl_contacto',
'ctrl_pedidoalmacen',
'usr_piso',
'usr_regpago',
'ctrl',
'sys_anio',
'usr_update_almacen',
'sys_update_family_info',
'sys_update_info',
'sys_upd_time',
'sys_upd_user',
'sys_upd_fecha',
'sys_disabledate_usr',
'sys_expiration_usr',
'sys_registrationdate_usr',
'sys_ntries_usr',
'global_rol_ciudadano_dep',
'global_rol_ciudadano',
'global_rol_gestion',
'global_rol_comacc',
'global_rol_procjur',
'globla_rol_ct',
'global_rol_cont',
'global_rol',
'global_rol_sid',
'global_rol_th',
'global_rol_jc3',
'global_rol_cej',
'global_rol_sipi',
'global_rol_zf',
'global_rol_dashboard',
'global_rol_cpanel',
'global_rol_siis',
'global_rol_inmuebles',
'global_rol_hojar',
'global_rol_ci',
'global_rol_gh',
'global_rol_me',
'usr_minequipo_grupo',
'usr_minequipo_lider',
'usr_jefe',
'usr_not_msj',
'usr_not',
'usr_entidad',
'user_dep',
'usr_dependencia',
'usr_status_sol',
'usr_type_vinculacion',
'usr_type_vinc',
'usr_rdnkey',
'usr_status',
'usr_status_nomina',
'usr_image',
'usr_sessini',
'usr_inicial',
'usr_nombresfull',
'Password',
'id_fk',
'idusrglobal',
'usr_name',
'usr_lname',
'usr_extension',
'usr_email',
'usr_dep',
'usr_datebirth',
'usr_cargo',
'sys_user',
'sys_time',
'sys_date',
'groupid',
'global_rol_contratos',
'global_rol_almacen',
'active',
'Username' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'Username' => array( 'simple_grid_field2',
'simple_grid_field9' ),
'usr_email' => array( 'simple_grid_field4',
'simple_grid_field10' ),
'usr_name' => array( 'simple_grid_field5',
'simple_grid_field11' ),
'usr_lname' => array( 'simple_grid_field6',
'simple_grid_field12' ),
'usr_personalid' => array( 'simple_grid_field8',
'simple_grid_field13' ),
'global_rol_almacen' => array( 'simple_grid_field28',
'simple_grid_field29' ),
'global_rol_contratos' => array( 'simple_grid_field30',
'simple_grid_field31' ),
'sys_user' => array( 'simple_grid_field50',
'simple_grid_field53' ),
'sys_date' => array( 'simple_grid_field51',
'simple_grid_field54' ),
'sys_time' => array( 'simple_grid_field52',
'simple_grid_field55' ),
'usr_dep' => array( 'simple_grid_field65',
'simple_grid_field67' ),
'usr_cargo' => array( 'simple_grid_field66',
'simple_grid_field69' ),
'usr_extension' => array( 'simple_grid_field68',
'simple_grid_field71' ),
'usr_datebirth' => array( 'simple_grid_field70',
'simple_grid_field72' ),
'active' => array( 'simple_grid_field75',
'simple_grid_field77' ),
'groupid' => array( 'simple_grid_field76',
'simple_grid_field78' ),
'id_fk' => array( 'simple_grid_field',
'simple_grid_field14' ),
'phone' => array( 'simple_grid_field1',
'simple_grid_field15' ),
'usr_directivo' => array( 'simple_grid_field3',
'simple_grid_field16' ),
'usr_dep_sup' => array( 'simple_grid_field7',
'simple_grid_field17' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => true,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'add',
'inline_add',
'delete',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'master_info' ),
'grid' => array( 'simple_grid_field9',
'simple_grid_field2',
'simple_grid_field10',
'simple_grid_field4',
'simple_grid_field11',
'simple_grid_field5',
'simple_grid_field12',
'simple_grid_field6',
'simple_grid_field13',
'simple_grid_field8',
'simple_grid_field29',
'simple_grid_field28',
'simple_grid_field31',
'simple_grid_field30',
'simple_grid_field53',
'simple_grid_field50',
'simple_grid_field54',
'simple_grid_field51',
'simple_grid_field55',
'simple_grid_field52',
'simple_grid_field67',
'simple_grid_field65',
'simple_grid_field69',
'simple_grid_field66',
'simple_grid_field71',
'simple_grid_field68',
'simple_grid_field72',
'simple_grid_field70',
'simple_grid_field77',
'simple_grid_field75',
'simple_grid_field78',
'simple_grid_field76',
'simple_grid_field14',
'simple_grid_field',
'simple_grid_field15',
'simple_grid_field1',
'simple_grid_field16',
'simple_grid_field3',
'simple_grid_field17',
'simple_grid_field7',
'grid_edit',
'grid_inline_cancel',
'grid_view',
'grid_checkbox_head',
'grid_checkbox' ) ),
'formXtTags' => array( 'above-grid' => array( 'add_link',
'inlineadd_link',
'deleteselected_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'add' => 'above-grid',
'inline_add' => 'above-grid',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'master_info' => 'top',
'simple_grid_field9' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field77' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field78' => 'grid',
'simple_grid_field76' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field7' => 'grid',
'grid_edit' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_view' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid' ),
'itemLocations' => array( 'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field77' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field78' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field76' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'menu' => 3,
'search_panel' => 5,
'collapse_button' => 5,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'-' => array( '-3',
'-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'delete_selected' => array( 'delete_selected' ),
'delete' => array( 'delete' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'export' => array( 'export' ),
'export_selected' => array( 'export_selected' ),
'import' => array( 'import' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field78',
'search_panel_field1',
'search_panel_field2',
'search_panel_field',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field8',
'search_panel_field7',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field15',
'search_panel_field14',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field26',
'search_panel_field27',
'search_panel_field28',
'search_panel_field29',
'search_panel_field31',
'search_panel_field30',
'search_panel_field32',
'search_panel_field33',
'search_panel_field34',
'search_panel_field36',
'search_panel_field35',
'search_panel_field37',
'search_panel_field38',
'search_panel_field39',
'search_panel_field41',
'search_panel_field40',
'search_panel_field42',
'search_panel_field43',
'search_panel_field44',
'search_panel_field45',
'search_panel_field47',
'search_panel_field46',
'search_panel_field48',
'search_panel_field50',
'search_panel_field51',
'search_panel_field52',
'search_panel_field49',
'search_panel_field54',
'search_panel_field53',
'search_panel_field55',
'search_panel_field57',
'search_panel_field56',
'search_panel_field58',
'search_panel_field59',
'search_panel_field61',
'search_panel_field60',
'search_panel_field62',
'search_panel_field64',
'search_panel_field63',
'search_panel_field65',
'search_panel_field66',
'search_panel_field68',
'search_panel_field67',
'search_panel_field69',
'search_panel_field70',
'search_panel_field71',
'search_panel_field72',
'search_panel_field73',
'search_panel_field74',
'search_panel_field75',
'search_panel_field76',
'search_panel_field77',
'search_panel_field79',
'search_panel_field80',
'search_panel_field81',
'search_panel_field82' ),
'master_info' => array( 'master_info' ),
'logo' => array( 'logo1' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'grid_field' => array( 'simple_grid_field2',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field8',
'simple_grid_field28',
'simple_grid_field30',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field68',
'simple_grid_field70',
'simple_grid_field75',
'simple_grid_field76',
'simple_grid_field',
'simple_grid_field1',
'simple_grid_field3',
'simple_grid_field7' ),
'grid_field_label' => array( 'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field29',
'simple_grid_field31',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field67',
'simple_grid_field69',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field77',
'simple_grid_field78',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17' ),
'grid_edit' => array( 'grid_edit' ),
'grid_view' => array( 'grid_view' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'expand_button' => array( 'expand_button' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'Username_fieldheadercolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'usr_email_fieldheadercolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'usr_name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'usr_lname_fieldheadercolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'usr_personalid_fieldheadercolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'global_rol_almacen_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'global_rol_contratos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'sys_user_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'sys_date_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'sys_time_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'usr_dep_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'usr_cargo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'usr_extension_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'usr_datebirth_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'active_fieldheadercolumn' ),
'items' => array( 'simple_grid_field77' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'groupid_fieldheadercolumn' ),
'items' => array( 'simple_grid_field78' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'id_fk_fieldheadercolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'phone_fieldheadercolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'usr_directivo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'usr_dep_sup_fieldheadercolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'edit_column',
'inline_cancel',
'view_column' ),
'items' => array( 'grid_edit',
'grid_inline_cancel',
'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Username_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'usr_email_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'usr_name_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'usr_lname_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'usr_personalid_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'global_rol_almacen_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'global_rol_contratos_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'sys_user_fieldcolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'sys_date_fieldcolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'sys_time_fieldcolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'usr_dep_fieldcolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'usr_cargo_fieldcolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'usr_extension_fieldcolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'usr_datebirth_fieldcolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'active_fieldcolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'groupid_fieldcolumn' ),
'items' => array( 'simple_grid_field76' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'id_fk_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'phone_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'usr_directivo_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'usr_dep_sup_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 22,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'inline_add',
'delete' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'Username',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'Username',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'usr_email',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'usr_email',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'usr_name',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'usr_name',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'usr_lname',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'usr_lname',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'usr_personalid',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'usr_personalid',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'global_rol_almacen',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'global_rol_almacen',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'global_rol_contratos',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'global_rol_contratos',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'sys_user',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'sys_user',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'sys_date',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'sys_date',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'sys_time',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'sys_time',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'usr_dep',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'usr_dep',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'usr_cargo',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'usr_cargo',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'usr_extension',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'usr_extension',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'usr_datebirth',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'usr_datebirth',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field77' ),
'field' => 'active',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'active',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field78' ),
'field' => 'groupid',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field76' ),
'field' => 'groupid',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'id_fk',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'id_fk',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'phone',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'phone',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'usr_directivo',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'usr_directivo',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'usr_dep_sup',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'usr_dep_sup',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_edit',
'grid_inline_cancel',
'grid_view' ),
'columnName' => 'list-icons' ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ),
'columnName' => 'checkbox' ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ),
'columnName' => 'checkbox' ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ),
'columnName' => 'checkbox' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'delete_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export',
'-2',
'import' ) ),
'-3' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'delete' => array( 'type' => 'delete' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add',
'popup' => true ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'import' => array( 'type' => 'import' ),
'-2' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field68',
'search_panel_field82',
'search_panel_field81',
'search_panel_field80',
'search_panel_field79',
'search_panel_field78',
'search_panel_field77',
'search_panel_field76',
'search_panel_field75',
'search_panel_field74',
'search_panel_field73',
'search_panel_field72',
'search_panel_field71',
'search_panel_field70',
'search_panel_field69',
'search_panel_field67',
'search_panel_field66',
'search_panel_field65',
'search_panel_field63',
'search_panel_field62',
'search_panel_field60',
'search_panel_field59',
'search_panel_field58',
'search_panel_field56',
'search_panel_field55',
'search_panel_field53',
'search_panel_field49',
'search_panel_field48',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field',
'search_panel_field64',
'search_panel_field61',
'search_panel_field57',
'search_panel_field54',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field47',
'search_panel_field41',
'search_panel_field36',
'search_panel_field31',
'search_panel_field15',
'search_panel_field8',
'search_panel_field2',
'search_panel_field1' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field78' => array( 'field' => 'estado_vinculacion_mincit',
'type' => 'search_panel_field' ),
'search_panel_field1' => array( 'field' => 'Username',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field2' => array( 'field' => 'active',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field' => array( 'field' => 'idusrglobal',
'type' => 'search_panel_field' ),
'search_panel_field3' => array( 'field' => 'id_fk',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field4' => array( 'field' => 'Password',
'type' => 'search_panel_field' ),
'search_panel_field5' => array( 'field' => 'usr_nombresfull',
'type' => 'search_panel_field' ),
'search_panel_field6' => array( 'field' => 'usr_inicial',
'type' => 'search_panel_field' ),
'search_panel_field8' => array( 'field' => 'global_rol_almacen',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field7' => array( 'field' => 'usr_sessini',
'type' => 'search_panel_field' ),
'search_panel_field9' => array( 'field' => 'usr_image',
'type' => 'search_panel_field' ),
'search_panel_field10' => array( 'field' => 'usr_status_nomina',
'type' => 'search_panel_field' ),
'search_panel_field11' => array( 'field' => 'usr_status',
'type' => 'search_panel_field' ),
'search_panel_field12' => array( 'field' => 'usr_rdnkey',
'type' => 'search_panel_field' ),
'search_panel_field13' => array( 'field' => 'usr_type_vinc',
'type' => 'search_panel_field' ),
'search_panel_field15' => array( 'field' => 'global_rol_contratos',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field14' => array( 'field' => 'usr_type_vinculacion',
'type' => 'search_panel_field' ),
'search_panel_field16' => array( 'field' => 'usr_status_sol',
'type' => 'search_panel_field' ),
'search_panel_field17' => array( 'field' => 'usr_dependencia',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field18' => array( 'field' => 'user_dep',
'type' => 'search_panel_field' ),
'search_panel_field19' => array( 'field' => 'usr_entidad',
'type' => 'search_panel_field' ),
'search_panel_field20' => array( 'field' => 'usr_not',
'type' => 'search_panel_field' ),
'search_panel_field21' => array( 'field' => 'usr_not_msj',
'type' => 'search_panel_field' ),
'search_panel_field22' => array( 'field' => 'usr_jefe',
'type' => 'search_panel_field' ),
'search_panel_field23' => array( 'field' => 'usr_minequipo_lider',
'type' => 'search_panel_field' ),
'search_panel_field24' => array( 'field' => 'usr_minequipo_grupo',
'type' => 'search_panel_field' ),
'search_panel_field25' => array( 'field' => 'global_rol_me',
'type' => 'search_panel_field' ),
'search_panel_field26' => array( 'field' => 'global_rol_gh',
'type' => 'search_panel_field' ),
'search_panel_field27' => array( 'field' => 'global_rol_ci',
'type' => 'search_panel_field' ),
'search_panel_field28' => array( 'field' => 'global_rol_hojar',
'type' => 'search_panel_field' ),
'search_panel_field29' => array( 'field' => 'global_rol_inmuebles',
'type' => 'search_panel_field' ),
'search_panel_field31' => array( 'field' => 'groupid',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field30' => array( 'field' => 'global_rol_siis',
'type' => 'search_panel_field' ),
'search_panel_field32' => array( 'field' => 'global_rol_cpanel',
'type' => 'search_panel_field' ),
'search_panel_field33' => array( 'field' => 'global_rol_dashboard',
'type' => 'search_panel_field' ),
'search_panel_field34' => array( 'field' => 'global_rol_zf',
'type' => 'search_panel_field' ),
'search_panel_field36' => array( 'field' => 'sys_date',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field35' => array( 'field' => 'global_rol_sipi',
'type' => 'search_panel_field' ),
'search_panel_field37' => array( 'field' => 'global_rol_cej',
'type' => 'search_panel_field' ),
'search_panel_field38' => array( 'field' => 'global_rol_jc3',
'type' => 'search_panel_field' ),
'search_panel_field39' => array( 'field' => 'global_rol_th',
'type' => 'search_panel_field' ),
'search_panel_field41' => array( 'field' => 'sys_time',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field40' => array( 'field' => 'global_rol_sid',
'type' => 'search_panel_field' ),
'search_panel_field42' => array( 'field' => 'global_rol',
'type' => 'search_panel_field' ),
'search_panel_field43' => array( 'field' => 'global_rol_cont',
'type' => 'search_panel_field' ),
'search_panel_field44' => array( 'field' => 'globla_rol_ct',
'type' => 'search_panel_field' ),
'search_panel_field45' => array( 'field' => 'global_rol_procjur',
'type' => 'search_panel_field' ),
'search_panel_field47' => array( 'field' => 'sys_user',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field46' => array( 'field' => 'global_rol_comacc',
'type' => 'search_panel_field' ),
'search_panel_field48' => array( 'field' => 'global_rol_gestion',
'type' => 'search_panel_field' ),
'search_panel_field50' => array( 'field' => 'usr_cargo',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field51' => array( 'field' => 'usr_datebirth',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field52' => array( 'field' => 'usr_dep',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field49' => array( 'field' => 'global_rol_ciudadano',
'type' => 'search_panel_field' ),
'search_panel_field54' => array( 'field' => 'usr_email',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field53' => array( 'field' => 'global_rol_ciudadano_dep',
'type' => 'search_panel_field' ),
'search_panel_field55' => array( 'field' => 'sys_ntries_usr',
'type' => 'search_panel_field' ),
'search_panel_field57' => array( 'field' => 'usr_extension',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field56' => array( 'field' => 'sys_registrationdate_usr',
'type' => 'search_panel_field' ),
'search_panel_field58' => array( 'field' => 'sys_expiration_usr',
'type' => 'search_panel_field' ),
'search_panel_field59' => array( 'field' => 'sys_disabledate_usr',
'type' => 'search_panel_field' ),
'search_panel_field61' => array( 'field' => 'usr_lname',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field60' => array( 'field' => 'sys_upd_fecha',
'type' => 'search_panel_field' ),
'search_panel_field62' => array( 'field' => 'sys_upd_user',
'type' => 'search_panel_field' ),
'search_panel_field64' => array( 'field' => 'usr_name',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field63' => array( 'field' => 'sys_upd_time',
'type' => 'search_panel_field' ),
'search_panel_field65' => array( 'field' => 'sys_update_info',
'type' => 'search_panel_field' ),
'search_panel_field66' => array( 'field' => 'sys_update_family_info',
'type' => 'search_panel_field' ),
'search_panel_field68' => array( 'field' => 'usr_personalid',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field67' => array( 'field' => 'usr_update_almacen',
'type' => 'search_panel_field' ),
'search_panel_field69' => array( 'field' => 'sys_anio',
'type' => 'search_panel_field' ),
'search_panel_field70' => array( 'field' => 'ctrl',
'type' => 'search_panel_field' ),
'search_panel_field71' => array( 'field' => 'usr_regpago',
'type' => 'search_panel_field' ),
'search_panel_field72' => array( 'field' => 'usr_piso',
'type' => 'search_panel_field' ),
'search_panel_field73' => array( 'field' => 'ctrl_pedidoalmacen',
'type' => 'search_panel_field' ),
'search_panel_field74' => array( 'field' => 'ctrl_contacto',
'type' => 'search_panel_field' ),
'search_panel_field75' => array( 'field' => 'usr_emergencia',
'type' => 'search_panel_field' ),
'search_panel_field76' => array( 'field' => 'upd_date',
'type' => 'search_panel_field' ),
'search_panel_field77' => array( 'field' => 'habilita_almacen',
'type' => 'search_panel_field' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'funcionario' => 'true' ) ),
'logo1' => array( 'type' => 'logo' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'search_panel_field79' => array( 'field' => 'phone',
'type' => 'search_panel_field',
'required' => false ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'search_panel_field80' => array( 'field' => 'usr_directivo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field81' => array( 'field' => 'usr_dep_sup',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field82' => array( 'field' => 'phone1',
'type' => 'search_panel_field' ),
'simple_grid_field2' => array( 'field' => 'Username',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field9' => array( 'type' => 'grid_field_label',
'field' => 'Username',
'clickSort' => true ),
'simple_grid_field4' => array( 'field' => 'usr_email',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field10' => array( 'type' => 'grid_field_label',
'field' => 'usr_email',
'clickSort' => true ),
'simple_grid_field5' => array( 'field' => 'usr_name',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'usr_name',
'clickSort' => true ),
'simple_grid_field6' => array( 'field' => 'usr_lname',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field12' => array( 'type' => 'grid_field_label',
'field' => 'usr_lname',
'clickSort' => true ),
'simple_grid_field8' => array( 'field' => 'usr_personalid',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field13' => array( 'type' => 'grid_field_label',
'field' => 'usr_personalid',
'clickSort' => true ),
'simple_grid_field28' => array( 'field' => 'global_rol_almacen',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'global_rol_almacen',
'clickSort' => true ),
'simple_grid_field30' => array( 'field' => 'global_rol_contratos',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'global_rol_contratos',
'clickSort' => true ),
'simple_grid_field50' => array( 'field' => 'sys_user',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'sys_user',
'clickSort' => true ),
'simple_grid_field51' => array( 'field' => 'sys_date',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'sys_date',
'clickSort' => true ),
'simple_grid_field52' => array( 'field' => 'sys_time',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'sys_time',
'clickSort' => true ),
'simple_grid_field65' => array( 'field' => 'usr_dep',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'usr_dep',
'clickSort' => true ),
'simple_grid_field66' => array( 'field' => 'usr_cargo',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'usr_cargo',
'clickSort' => true ),
'simple_grid_field68' => array( 'field' => 'usr_extension',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'usr_extension',
'clickSort' => true ),
'simple_grid_field70' => array( 'field' => 'usr_datebirth',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'usr_datebirth',
'clickSort' => true ),
'simple_grid_field75' => array( 'field' => 'active',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field77' => array( 'type' => 'grid_field_label',
'field' => 'active',
'clickSort' => true ),
'simple_grid_field76' => array( 'field' => 'groupid',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field78' => array( 'type' => 'grid_field_label',
'field' => 'groupid',
'clickSort' => true ),
'simple_grid_field' => array( 'field' => 'id_fk',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field14' => array( 'type' => 'grid_field_label',
'field' => 'id_fk' ),
'simple_grid_field1' => array( 'field' => 'phone',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field15' => array( 'type' => 'grid_field_label',
'field' => 'phone' ),
'simple_grid_field3' => array( 'field' => 'usr_directivo',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field16' => array( 'type' => 'grid_field_label',
'field' => 'usr_directivo' ),
'simple_grid_field7' => array( 'field' => 'usr_dep_sup',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field17' => array( 'type' => 'grid_field_label',
'field' => 'usr_dep_sup' ),
'grid_edit' => array( 'type' => 'grid_edit',
'popup' => true ),
'grid_view' => array( 'type' => 'grid_view',
'popup' => true ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'expand_button' => array( 'type' => 'expand_button' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>