<?php
			$optionsArray = array( 'totals' => array( 'PAA_ID' => array( 'totalsType' => '' ),
'PROD_ID' => array( 'totalsType' => '' ),
'COD_UNSPSC' => array( 'totalsType' => '' ),
'DESCRIPCION' => array( 'totalsType' => '' ),
'MES_INICIO' => array( 'totalsType' => '' ),
'MES_PRESENTA' => array( 'totalsType' => '' ),
'DURACION_CONTRATO' => array( 'totalsType' => '' ),
'DURACION_ESTIMADA_DMA' => array( 'totalsType' => '' ),
'MODALIDAD' => array( 'totalsType' => '' ),
'FUENTE_RECURSOS' => array( 'totalsType' => '' ),
'VALOR' => array( 'totalsType' => '' ),
'VALOR_VIGENCIA' => array( 'totalsType' => '' ),
'VALOR_VIGENCIA_FUTURA' => array( 'totalsType' => '' ),
'VF' => array( 'totalsType' => '' ),
'ESTADO_VF' => array( 'totalsType' => '' ),
'UNIDAD_CONTRATACION' => array( 'totalsType' => '' ),
'COD_UBICACION' => array( 'totalsType' => '' ),
'RESPONSABLE_NOMBRE' => array( 'totalsType' => '' ),
'RESPONSABLE_TELEFONO' => array( 'totalsType' => '' ),
'RESPONSABLE_EMAIL' => array( 'totalsType' => '' ),
'responsable' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'sys_status' => array( 'totalsType' => '' ),
'REQ_MAILNOT' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'PAA_ID',
'PROD_ID',
'COD_UNSPSC',
'DESCRIPCION',
'MES_INICIO',
'MES_PRESENTA',
'DURACION_CONTRATO',
'DURACION_ESTIMADA_DMA',
'MODALIDAD',
'FUENTE_RECURSOS',
'VALOR',
'VALOR_VIGENCIA',
'VALOR_VIGENCIA_FUTURA',
'VF',
'ESTADO_VF',
'UNIDAD_CONTRATACION',
'COD_UBICACION',
'RESPONSABLE_NOMBRE',
'RESPONSABLE_TELEFONO',
'responsable',
'vigencia',
'sys_user',
'sys_date',
'sys_status',
'REQ_MAILNOT' ),
'exportFields' => array( 'PAA_ID',
'COD_UNSPSC',
'DESCRIPCION',
'MES_INICIO',
'MES_PRESENTA',
'DURACION_CONTRATO',
'DURACION_ESTIMADA_DMA',
'MODALIDAD',
'FUENTE_RECURSOS',
'VALOR',
'VALOR_VIGENCIA',
'VALOR_VIGENCIA_FUTURA',
'VF',
'ESTADO_VF',
'UNIDAD_CONTRATACION',
'COD_UBICACION',
'RESPONSABLE_NOMBRE',
'RESPONSABLE_TELEFONO',
'responsable',
'vigencia',
'sys_user',
'sys_date',
'sys_status',
'REQ_MAILNOT',
'PROD_ID' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PAA_ID' => array( 'export_field' ),
'PROD_ID' => array( 'export_field1' ),
'COD_UNSPSC' => array( 'export_field2' ),
'DESCRIPCION' => array( 'export_field3' ),
'MES_INICIO' => array( 'export_field5' ),
'MES_PRESENTA' => array( 'export_field6' ),
'DURACION_CONTRATO' => array( 'export_field7' ),
'DURACION_ESTIMADA_DMA' => array( 'export_field8' ),
'MODALIDAD' => array( 'export_field9' ),
'FUENTE_RECURSOS' => array( 'export_field10' ),
'VALOR' => array( 'export_field11' ),
'VALOR_VIGENCIA' => array( 'export_field12' ),
'VALOR_VIGENCIA_FUTURA' => array( 'export_field13' ),
'VF' => array( 'export_field14' ),
'ESTADO_VF' => array( 'export_field15' ),
'UNIDAD_CONTRATACION' => array( 'export_field16' ),
'COD_UBICACION' => array( 'export_field17' ),
'RESPONSABLE_NOMBRE' => array( 'export_field18' ),
'RESPONSABLE_TELEFONO' => array( 'export_field19' ),
'responsable' => array( 'export_field21' ),
'vigencia' => array( 'export_field22' ),
'sys_user' => array( 'export_field23' ),
'sys_date' => array( 'export_field24' ),
'sys_status' => array( 'export_field25' ),
'REQ_MAILNOT' => array( 'export_field28' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field2',
'export_field3',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field28',
'export_field1' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field28' => 'grid',
'export_field1' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field28' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field2',
'export_field3',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field28',
'export_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'PAA_ID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'PROD_ID',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'COD_UNSPSC',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'DESCRIPCION',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'MES_INICIO',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'MES_PRESENTA',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'DURACION_CONTRATO',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'DURACION_ESTIMADA_DMA',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'MODALIDAD',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'FUENTE_RECURSOS',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'VALOR',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'VALOR_VIGENCIA',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'VALOR_VIGENCIA_FUTURA',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'VF',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'ESTADO_VF',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'COD_UBICACION',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'RESPONSABLE_NOMBRE',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'RESPONSABLE_TELEFONO',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'responsable',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'vigencia',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'sys_date',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'sys_status',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'REQ_MAILNOT',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>