<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'secop_id',
'secop.nombre_entidad',
'secop.nit_entidad',
'secop.departamento',
'secop.ciudad',
'secop.localizaci_n',
'secop.orden',
'secop.sector',
'secop.rama',
'secop.entidad_centralizada',
'secop.proceso_de_compra',
'secop.id_contrato',
'secop.referencia_del_contrato',
'secop.estado_contrato',
'secop.codigo_de_categoria_principal',
'secop.descripcion_del_proceso',
'secop.tipo_de_contrato',
'secop.modalidad_de_contratacion',
'secop.justificacion_modalidad_de',
'secop.fecha_de_firma',
'secop.fecha_de_inicio_del_contrato',
'secop.fecha_de_fin_del_contrato',
'secop.fecha_de_inicio_de_ejecucion',
'secop.fecha_de_fin_de_ejecucion',
'secop.condiciones_de_entrega',
'secop.tipodocproveedor',
'secop.documento_proveedor',
'secop.proveedor_adjudicado',
'secop.es_grupo',
'secop.es_pyme',
'secop.habilita_pago_adelantado',
'secop.liquidaci_n',
'secop.obligaci_n_ambiental',
'secop.obligaciones_postconsumo',
'secop.reversion',
'secop.valor_del_contrato',
'secop.valor_de_pago_adelantado',
'secop.valor_facturado',
'secop.valor_pendiente_de_pago',
'secop.valor_pagado',
'secop.valor_amortizado',
'secop.valor_pendiente_de',
'secop.valor_pendiente_de_ejecucion',
'secop.estado_bpin',
'secop.c_digo_bpin',
'secop.anno_bpin',
'secop.saldo_cdp',
'secop.saldo_vigencia',
'secop.espostconflicto',
'secop.urlproceso.url',
'secop.destino_gasto',
'secop.origen_de_los_recursos',
'secop.d_as_adicionados',
'secop.puntos_del_acuerdo',
'secop.pilares_del_acuerdo' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'secop_id' => array( 'import_field' ),
'secop.nombre_entidad' => array( 'import_field1' ),
'secop.nit_entidad' => array( 'import_field2' ),
'secop.departamento' => array( 'import_field3' ),
'secop.ciudad' => array( 'import_field4' ),
'secop.localizaci_n' => array( 'import_field5' ),
'secop.orden' => array( 'import_field6' ),
'secop.sector' => array( 'import_field7' ),
'secop.rama' => array( 'import_field8' ),
'secop.entidad_centralizada' => array( 'import_field9' ),
'secop.proceso_de_compra' => array( 'import_field10' ),
'secop.id_contrato' => array( 'import_field11' ),
'secop.referencia_del_contrato' => array( 'import_field12' ),
'secop.estado_contrato' => array( 'import_field13' ),
'secop.codigo_de_categoria_principal' => array( 'import_field14' ),
'secop.descripcion_del_proceso' => array( 'import_field15' ),
'secop.tipo_de_contrato' => array( 'import_field16' ),
'secop.modalidad_de_contratacion' => array( 'import_field17' ),
'secop.justificacion_modalidad_de' => array( 'import_field18' ),
'secop.fecha_de_firma' => array( 'import_field19' ),
'secop.fecha_de_inicio_del_contrato' => array( 'import_field20' ),
'secop.fecha_de_fin_del_contrato' => array( 'import_field21' ),
'secop.fecha_de_inicio_de_ejecucion' => array( 'import_field22' ),
'secop.fecha_de_fin_de_ejecucion' => array( 'import_field23' ),
'secop.condiciones_de_entrega' => array( 'import_field24' ),
'secop.tipodocproveedor' => array( 'import_field25' ),
'secop.documento_proveedor' => array( 'import_field26' ),
'secop.proveedor_adjudicado' => array( 'import_field27' ),
'secop.es_grupo' => array( 'import_field28' ),
'secop.es_pyme' => array( 'import_field29' ),
'secop.habilita_pago_adelantado' => array( 'import_field30' ),
'secop.liquidaci_n' => array( 'import_field31' ),
'secop.obligaci_n_ambiental' => array( 'import_field32' ),
'secop.obligaciones_postconsumo' => array( 'import_field33' ),
'secop.reversion' => array( 'import_field34' ),
'secop.valor_del_contrato' => array( 'import_field35' ),
'secop.valor_de_pago_adelantado' => array( 'import_field36' ),
'secop.valor_facturado' => array( 'import_field37' ),
'secop.valor_pendiente_de_pago' => array( 'import_field38' ),
'secop.valor_pagado' => array( 'import_field39' ),
'secop.valor_amortizado' => array( 'import_field40' ),
'secop.valor_pendiente_de' => array( 'import_field41' ),
'secop.valor_pendiente_de_ejecucion' => array( 'import_field42' ),
'secop.estado_bpin' => array( 'import_field43' ),
'secop.c_digo_bpin' => array( 'import_field44' ),
'secop.anno_bpin' => array( 'import_field45' ),
'secop.saldo_cdp' => array( 'import_field46' ),
'secop.saldo_vigencia' => array( 'import_field47' ),
'secop.espostconflicto' => array( 'import_field48' ),
'secop.urlproceso.url' => array( 'import_field49' ),
'secop.destino_gasto' => array( 'import_field50' ),
'secop.origen_de_los_recursos' => array( 'import_field51' ),
'secop.d_as_adicionados' => array( 'import_field52' ),
'secop.puntos_del_acuerdo' => array( 'import_field53' ),
'secop.pilares_del_acuerdo' => array( 'import_field54' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid',
'import_field51' => 'grid',
'import_field52' => 'grid',
'import_field53' => 'grid',
'import_field54' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'secop_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'secop.nombre_entidad',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'secop.nit_entidad',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'secop.departamento',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'secop.ciudad',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'secop.localizaci_n',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'secop.orden',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'secop.sector',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'secop.rama',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'secop.entidad_centralizada',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'secop.proceso_de_compra',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'secop.id_contrato',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'secop.referencia_del_contrato',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'secop.estado_contrato',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'secop.codigo_de_categoria_principal',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'secop.descripcion_del_proceso',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'secop.tipo_de_contrato',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'secop.modalidad_de_contratacion',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'secop.justificacion_modalidad_de',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'secop.fecha_de_firma',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'secop.fecha_de_inicio_del_contrato',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'secop.fecha_de_fin_del_contrato',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'secop.fecha_de_inicio_de_ejecucion',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'secop.fecha_de_fin_de_ejecucion',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'secop.condiciones_de_entrega',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'secop.tipodocproveedor',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'secop.documento_proveedor',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'secop.proveedor_adjudicado',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'secop.es_grupo',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'secop.es_pyme',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'secop.habilita_pago_adelantado',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'secop.liquidaci_n',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'secop.obligaci_n_ambiental',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'secop.obligaciones_postconsumo',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'secop.reversion',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'secop.valor_del_contrato',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'secop.valor_de_pago_adelantado',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'secop.valor_facturado',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'secop.valor_pendiente_de_pago',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'secop.valor_pagado',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'secop.valor_amortizado',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'secop.valor_pendiente_de',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'secop.valor_pendiente_de_ejecucion',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'secop.estado_bpin',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'secop.c_digo_bpin',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'secop.anno_bpin',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'secop.saldo_cdp',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'secop.saldo_vigencia',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'secop.espostconflicto',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'secop.urlproceso.url',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'secop.destino_gasto',
'type' => 'import_field' ),
'import_field51' => array( 'field' => 'secop.origen_de_los_recursos',
'type' => 'import_field' ),
'import_field52' => array( 'field' => 'secop.d_as_adicionados',
'type' => 'import_field' ),
'import_field53' => array( 'field' => 'secop.puntos_del_acuerdo',
'type' => 'import_field' ),
'import_field54' => array( 'field' => 'secop.pilares_del_acuerdo',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>