<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'delete' => true,
'updateSelected' => false,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'secop_id' => array( 'totalsType' => '' ),
'secop.nombre_entidad' => array( 'totalsType' => '' ),
'secop.nit_entidad' => array( 'totalsType' => '' ),
'secop.departamento' => array( 'totalsType' => '' ),
'secop.ciudad' => array( 'totalsType' => '' ),
'secop.localizaci_n' => array( 'totalsType' => '' ),
'secop.orden' => array( 'totalsType' => '' ),
'secop.sector' => array( 'totalsType' => '' ),
'secop.rama' => array( 'totalsType' => '' ),
'secop.entidad_centralizada' => array( 'totalsType' => '' ),
'secop.proceso_de_compra' => array( 'totalsType' => '' ),
'secop.id_contrato' => array( 'totalsType' => '' ),
'secop.referencia_del_contrato' => array( 'totalsType' => '' ),
'secop.estado_contrato' => array( 'totalsType' => '' ),
'secop.codigo_de_categoria_principal' => array( 'totalsType' => '' ),
'secop.descripcion_del_proceso' => array( 'totalsType' => '' ),
'secop.tipo_de_contrato' => array( 'totalsType' => '' ),
'secop.modalidad_de_contratacion' => array( 'totalsType' => '' ),
'secop.justificacion_modalidad_de' => array( 'totalsType' => '' ),
'secop.fecha_de_firma' => array( 'totalsType' => '' ),
'secop.fecha_de_inicio_del_contrato' => array( 'totalsType' => '' ),
'secop.fecha_de_fin_del_contrato' => array( 'totalsType' => '' ),
'secop.fecha_de_inicio_de_ejecucion' => array( 'totalsType' => '' ),
'secop.fecha_de_fin_de_ejecucion' => array( 'totalsType' => '' ),
'secop.condiciones_de_entrega' => array( 'totalsType' => '' ),
'secop.tipodocproveedor' => array( 'totalsType' => '' ),
'secop.documento_proveedor' => array( 'totalsType' => '' ),
'secop.proveedor_adjudicado' => array( 'totalsType' => '' ),
'secop.es_grupo' => array( 'totalsType' => '' ),
'secop.es_pyme' => array( 'totalsType' => '' ),
'secop.habilita_pago_adelantado' => array( 'totalsType' => '' ),
'secop.liquidaci_n' => array( 'totalsType' => '' ),
'secop.obligaci_n_ambiental' => array( 'totalsType' => '' ),
'secop.obligaciones_postconsumo' => array( 'totalsType' => '' ),
'secop.reversion' => array( 'totalsType' => '' ),
'secop.valor_del_contrato' => array( 'totalsType' => '' ),
'secop.valor_de_pago_adelantado' => array( 'totalsType' => '' ),
'secop.valor_facturado' => array( 'totalsType' => '' ),
'secop.valor_pendiente_de_pago' => array( 'totalsType' => '' ),
'secop.valor_pagado' => array( 'totalsType' => '' ),
'secop.valor_amortizado' => array( 'totalsType' => '' ),
'secop.valor_pendiente_de' => array( 'totalsType' => '' ),
'secop.valor_pendiente_de_ejecucion' => array( 'totalsType' => '' ),
'secop.estado_bpin' => array( 'totalsType' => '' ),
'secop.c_digo_bpin' => array( 'totalsType' => '' ),
'secop.anno_bpin' => array( 'totalsType' => '' ),
'secop.saldo_cdp' => array( 'totalsType' => '' ),
'secop.saldo_vigencia' => array( 'totalsType' => '' ),
'secop.espostconflicto' => array( 'totalsType' => '' ),
'secop.urlproceso.url' => array( 'totalsType' => '' ),
'secop.destino_gasto' => array( 'totalsType' => '' ),
'secop.origen_de_los_recursos' => array( 'totalsType' => '' ),
'secop.d_as_adicionados' => array( 'totalsType' => '' ),
'secop.puntos_del_acuerdo' => array( 'totalsType' => '' ),
'secop.pilares_del_acuerdo' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'secop.urlproceso.url',
'secop.proceso_de_compra',
'secop.id_contrato',
'secop.referencia_del_contrato',
'secop.fecha_de_inicio_del_contrato',
'secop.fecha_de_fin_del_contrato',
'secop.documento_proveedor',
'secop.proveedor_adjudicado',
'secop.c_digo_bpin',
'secop.anno_bpin',
'secop.estado_contrato',
'secop.nit_entidad',
'secop.nombre_entidad' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'secop.anno_bpin',
'secop_id',
'secop.valor_pendiente_de_pago',
'secop.valor_pendiente_de_ejecucion',
'secop.valor_pendiente_de',
'secop.valor_pagado',
'secop.valor_facturado',
'secop.valor_del_contrato',
'secop.valor_de_pago_adelantado',
'secop.valor_amortizado',
'secop.urlproceso.url',
'secop.tipodocproveedor',
'secop.tipo_de_contrato',
'secop.sector',
'secop.saldo_vigencia',
'secop.saldo_cdp',
'secop.reversion',
'secop.referencia_del_contrato',
'secop.rama',
'secop.puntos_del_acuerdo',
'secop.proveedor_adjudicado',
'secop.proceso_de_compra',
'secop.pilares_del_acuerdo',
'secop.origen_de_los_recursos',
'secop.orden',
'secop.obligaciones_postconsumo',
'secop.obligaci_n_ambiental',
'secop.nombre_entidad',
'secop.nit_entidad',
'secop.modalidad_de_contratacion',
'secop.localizaci_n',
'secop.liquidaci_n',
'secop.justificacion_modalidad_de',
'secop.id_contrato',
'secop.habilita_pago_adelantado',
'secop.fecha_de_inicio_del_contrato',
'secop.fecha_de_inicio_de_ejecucion',
'secop.fecha_de_firma',
'secop.fecha_de_fin_del_contrato',
'secop.fecha_de_fin_de_ejecucion',
'secop.estado_contrato',
'secop.estado_bpin',
'secop.espostconflicto',
'secop.es_pyme',
'secop.es_grupo',
'secop.entidad_centralizada',
'secop.documento_proveedor',
'secop.destino_gasto',
'secop.descripcion_del_proceso',
'secop.departamento',
'secop.d_as_adicionados',
'secop.condiciones_de_entrega',
'secop.codigo_de_categoria_principal',
'secop.ciudad',
'secop.c_digo_bpin' ),
'filterFields' => array( 'secop.estado_contrato' ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'secop.urlproceso.url' => array( 'simple_grid_field3',
'simple_grid_field4' ),
'secop.proceso_de_compra' => array( 'simple_grid_field10',
'simple_grid_field13' ),
'secop.id_contrato' => array( 'simple_grid_field11',
'simple_grid_field14' ),
'secop.referencia_del_contrato' => array( 'simple_grid_field12',
'simple_grid_field15' ),
'secop.fecha_de_inicio_del_contrato' => array( 'simple_grid_field20',
'simple_grid_field22' ),
'secop.fecha_de_fin_del_contrato' => array( 'simple_grid_field21',
'simple_grid_field23' ),
'secop.documento_proveedor' => array( 'simple_grid_field26',
'simple_grid_field28' ),
'secop.proveedor_adjudicado' => array( 'simple_grid_field27',
'simple_grid_field29' ),
'secop.c_digo_bpin' => array( 'simple_grid_field44',
'simple_grid_field46' ),
'secop.anno_bpin' => array( 'simple_grid_field45',
'simple_grid_field47' ),
'secop.estado_contrato' => array( 'simple_grid_field',
'simple_grid_field5' ),
'secop.nit_entidad' => array( 'simple_grid_field2',
'simple_grid_field6' ),
'secop.nombre_entidad' => array( 'simple_grid_field1',
'simple_grid_field7' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => true,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel',
'filter_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'add',
'delete',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ),
'grid' => array( 'simple_grid_field4',
'simple_grid_field3',
'simple_grid_field13',
'simple_grid_field10',
'simple_grid_field14',
'simple_grid_field11',
'simple_grid_field15',
'simple_grid_field12',
'simple_grid_field22',
'simple_grid_field20',
'simple_grid_field23',
'simple_grid_field21',
'simple_grid_field28',
'simple_grid_field26',
'simple_grid_field29',
'simple_grid_field27',
'simple_grid_field46',
'simple_grid_field44',
'simple_grid_field47',
'simple_grid_field45',
'simple_grid_field5',
'simple_grid_field',
'simple_grid_field6',
'simple_grid_field2',
'simple_grid_field7',
'simple_grid_field1',
'grid_edit',
'grid_view',
'grid_checkbox_head',
'grid_checkbox' ) ),
'formXtTags' => array( 'above-grid' => array( 'add_link',
'deleteselected_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'filter_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'add' => 'above-grid',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field4' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field1' => 'grid',
'grid_edit' => 'grid',
'grid_view' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid' ),
'itemLocations' => array( 'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'menu' => 3,
'search_panel' => 5,
'filter_panel' => 3,
'collapse_button' => 5,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'filter_panel_field' => array( 'filter_panel_field' ),
'filter_panel' => array( 'filter_panel' ),
'-' => array( '-3',
'-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'delete_selected' => array( 'delete_selected' ),
'delete' => array( 'delete' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'export' => array( 'export' ),
'export_selected' => array( 'export_selected' ),
'import' => array( 'import' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field26',
'search_panel_field27',
'search_panel_field28',
'search_panel_field29',
'search_panel_field30',
'search_panel_field31',
'search_panel_field32',
'search_panel_field33',
'search_panel_field34',
'search_panel_field35',
'search_panel_field36',
'search_panel_field37',
'search_panel_field38',
'search_panel_field39',
'search_panel_field40',
'search_panel_field41',
'search_panel_field42',
'search_panel_field43',
'search_panel_field44',
'search_panel_field45',
'search_panel_field46',
'search_panel_field47',
'search_panel_field48',
'search_panel_field49',
'search_panel_field50',
'search_panel_field51',
'search_panel_field52',
'search_panel_field53',
'search_panel_field54' ),
'logo' => array( 'logo1' ),
'grid_field' => array( 'simple_grid_field3',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field',
'simple_grid_field2',
'simple_grid_field1' ),
'grid_field_label' => array( 'simple_grid_field4',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7' ),
'grid_edit' => array( 'grid_edit' ),
'grid_view' => array( 'grid_view' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'secop_urlproceso_url_fieldheadercolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'secop_proceso_de_compra_fieldheadercolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'secop_id_contrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'secop_referencia_del_contrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'secop_fecha_de_inicio_del_contrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'secop_fecha_de_fin_del_contrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'secop_documento_proveedor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'secop_proveedor_adjudicado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'secop_c_digo_bpin_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'secop_anno_bpin_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'secop_estado_contrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'secop_nit_entidad_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'secop_nombre_entidad_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'edit_column',
'view_column' ),
'items' => array( 'grid_edit',
'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'secop_urlproceso_url_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'secop_proceso_de_compra_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'secop_id_contrato_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'secop_referencia_del_contrato_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'secop_fecha_de_inicio_del_contrato_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'secop_fecha_de_fin_del_contrato_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'secop_documento_proveedor_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'secop_proveedor_adjudicado_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'secop_c_digo_bpin_fieldcolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'secop_anno_bpin_fieldcolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'secop_estado_contrato_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'secop_nit_entidad_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'secop_nombre_entidad_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 15,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel',
'filter_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'delete' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'secop.urlproceso.url',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'secop.urlproceso.url',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'secop.proceso_de_compra',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'secop.proceso_de_compra',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'secop.id_contrato',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'secop.id_contrato',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'secop.referencia_del_contrato',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'secop.referencia_del_contrato',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'secop.fecha_de_inicio_del_contrato',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'secop.fecha_de_inicio_del_contrato',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'secop.fecha_de_fin_del_contrato',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'secop.fecha_de_fin_del_contrato',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'secop.documento_proveedor',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'secop.documento_proveedor',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'secop.proveedor_adjudicado',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'secop.proveedor_adjudicado',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'secop.c_digo_bpin',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'secop.c_digo_bpin',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'secop.anno_bpin',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'secop.anno_bpin',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'secop.estado_contrato',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'secop.estado_contrato',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'secop.nit_entidad',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'secop.nit_entidad',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'secop.nombre_entidad',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'secop.nombre_entidad',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_edit',
'grid_view' ),
'columnName' => 'list-icons' ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ),
'columnName' => 'checkbox' ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ),
'columnName' => 'checkbox' ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ),
'columnName' => 'checkbox' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'delete_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export',
'-2',
'import' ) ),
'filter_panel_field' => array( 'field' => 'secop.estado_contrato',
'type' => 'filter_panel_field' ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array( 'filter_panel_field' ) ),
'-3' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'delete' => array( 'type' => 'delete' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'import' => array( 'type' => 'import' ),
'-2' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field54',
'search_panel_field53',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'secop.anno_bpin',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field1' => array( 'field' => 'secop.c_digo_bpin',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field2' => array( 'field' => 'secop.ciudad',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field3' => array( 'field' => 'secop.codigo_de_categoria_principal',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field4' => array( 'field' => 'secop.condiciones_de_entrega',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field5' => array( 'field' => 'secop.d_as_adicionados',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field6' => array( 'field' => 'secop.departamento',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field7' => array( 'field' => 'secop.descripcion_del_proceso',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field8' => array( 'field' => 'secop.destino_gasto',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field9' => array( 'field' => 'secop.documento_proveedor',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field10' => array( 'field' => 'secop.entidad_centralizada',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field11' => array( 'field' => 'secop.es_grupo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field12' => array( 'field' => 'secop.es_pyme',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field13' => array( 'field' => 'secop.espostconflicto',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field14' => array( 'field' => 'secop.estado_bpin',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field15' => array( 'field' => 'secop.estado_contrato',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field16' => array( 'field' => 'secop.fecha_de_fin_de_ejecucion',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field17' => array( 'field' => 'secop.fecha_de_fin_del_contrato',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field18' => array( 'field' => 'secop.fecha_de_firma',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field19' => array( 'field' => 'secop.fecha_de_inicio_de_ejecucion',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field20' => array( 'field' => 'secop.fecha_de_inicio_del_contrato',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field21' => array( 'field' => 'secop.habilita_pago_adelantado',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field22' => array( 'field' => 'secop.id_contrato',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field23' => array( 'field' => 'secop.justificacion_modalidad_de',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field24' => array( 'field' => 'secop.liquidaci_n',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field25' => array( 'field' => 'secop.localizaci_n',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field26' => array( 'field' => 'secop.modalidad_de_contratacion',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field27' => array( 'field' => 'secop.nit_entidad',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field28' => array( 'field' => 'secop.nombre_entidad',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field29' => array( 'field' => 'secop.obligaci_n_ambiental',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field30' => array( 'field' => 'secop.obligaciones_postconsumo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field31' => array( 'field' => 'secop.orden',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field32' => array( 'field' => 'secop.origen_de_los_recursos',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field33' => array( 'field' => 'secop.pilares_del_acuerdo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field34' => array( 'field' => 'secop.proceso_de_compra',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field35' => array( 'field' => 'secop.proveedor_adjudicado',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field36' => array( 'field' => 'secop.puntos_del_acuerdo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field37' => array( 'field' => 'secop.rama',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field38' => array( 'field' => 'secop.referencia_del_contrato',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field39' => array( 'field' => 'secop.reversion',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field40' => array( 'field' => 'secop.saldo_cdp',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field41' => array( 'field' => 'secop.saldo_vigencia',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field42' => array( 'field' => 'secop.sector',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field43' => array( 'field' => 'secop.tipo_de_contrato',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field44' => array( 'field' => 'secop.tipodocproveedor',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field45' => array( 'field' => 'secop.urlproceso.url',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field46' => array( 'field' => 'secop.valor_amortizado',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field47' => array( 'field' => 'secop.valor_de_pago_adelantado',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field48' => array( 'field' => 'secop.valor_del_contrato',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field49' => array( 'field' => 'secop.valor_facturado',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field50' => array( 'field' => 'secop.valor_pagado',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field51' => array( 'field' => 'secop.valor_pendiente_de',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field52' => array( 'field' => 'secop.valor_pendiente_de_ejecucion',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field53' => array( 'field' => 'secop.valor_pendiente_de_pago',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field54' => array( 'field' => 'secop_id',
'type' => 'search_panel_field',
'required' => false ),
'logo1' => array( 'type' => 'logo' ),
'simple_grid_field3' => array( 'field' => 'secop.urlproceso.url',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field4' => array( 'type' => 'grid_field_label',
'field' => 'secop.urlproceso.url' ),
'simple_grid_field10' => array( 'field' => 'secop.proceso_de_compra',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field13' => array( 'type' => 'grid_field_label',
'field' => 'secop.proceso_de_compra' ),
'simple_grid_field11' => array( 'field' => 'secop.id_contrato',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field14' => array( 'type' => 'grid_field_label',
'field' => 'secop.id_contrato' ),
'simple_grid_field12' => array( 'field' => 'secop.referencia_del_contrato',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field15' => array( 'type' => 'grid_field_label',
'field' => 'secop.referencia_del_contrato' ),
'simple_grid_field20' => array( 'field' => 'secop.fecha_de_inicio_del_contrato',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'secop.fecha_de_inicio_del_contrato' ),
'simple_grid_field21' => array( 'field' => 'secop.fecha_de_fin_del_contrato',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field23' => array( 'type' => 'grid_field_label',
'field' => 'secop.fecha_de_fin_del_contrato' ),
'simple_grid_field26' => array( 'field' => 'secop.documento_proveedor',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field28' => array( 'type' => 'grid_field_label',
'field' => 'secop.documento_proveedor' ),
'simple_grid_field27' => array( 'field' => 'secop.proveedor_adjudicado',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'secop.proveedor_adjudicado' ),
'simple_grid_field44' => array( 'field' => 'secop.c_digo_bpin',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'secop.c_digo_bpin' ),
'simple_grid_field45' => array( 'field' => 'secop.anno_bpin',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'secop.anno_bpin' ),
'simple_grid_field' => array( 'field' => 'secop.estado_contrato',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field5' => array( 'type' => 'grid_field_label',
'field' => 'secop.estado_contrato' ),
'simple_grid_field2' => array( 'field' => 'secop.nit_entidad',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'secop.nit_entidad' ),
'simple_grid_field1' => array( 'field' => 'secop.nombre_entidad',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'secop.nombre_entidad' ),
'grid_edit' => array( 'type' => 'grid_edit' ),
'grid_view' => array( 'type' => 'grid_view' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>