<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_000_global_f  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;

		$this->events["AfterAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, &$pageObject)
{

		
$sql = DB::prepareSQL("UPDATE sep2.000_global
LEFT JOIN sep2.q_ctrl_saldo_000 ON sep2.000_global.VIGENCIA = sep2.q_ctrl_saldo_000.VIGENCIA 
AND sep2.000_global.UEJ = sep2.q_ctrl_saldo_000.UEJ 
SET sep2.000_global.SALDO =
IF
	(
		sep2.q_ctrl_saldo_000.UTILIZADO IS NULL,
		sep2.000_global.PRESUPUESTO,(
		sep2.000_global.PRESUPUESTO - sep2.q_ctrl_saldo_000.UTILIZADO 
	));");
DB::Exec( $sql );


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
sep2.000_global
SET
sep2.000_global.SALDO = sep2.000_global.PRESUPUESTO;");
DB::Exec( $sql );


$sql = DB::prepareSQL("UPDATE
sep2.000_global
SET
sep2.000_global.UTILIZADO = (sep2.000_global.PRESUPUESTO - sep2.000_global.SALDO);");
DB::Exec( $sql );







// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
