<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_001_rubro  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterEdit"]=true;


		$this->events["BeforeAdd"]=true;


		$this->events["BeforeEdit"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["AfterDelete"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE sep2.000_global
INNER JOIN sep2.q_ctrl_saldo_000 ON sep2.000_global.VIGENCIA = sep2.q_ctrl_saldo_000.VIGENCIA 
AND sep2.000_global.UEJ = sep2.q_ctrl_saldo_000.UEJ 
SET sep2.000_global.SALDO = ( sep2.000_global.PRESUPUESTO - sep2.q_ctrl_saldo_000.UTILIZADO );");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

		if($values['PRESUPUESTO'] > $values['SALDO']){
$message = "El valor solicitado, supera el valor programado en el producto";
$return = false;
}
else 
{
return true;
}

;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, &$pageObject)
{

		if($values['PRESUPUESTO'] > $values['SALDO']){
$message = "El valor solicitado, supera el valor programado en el producto";
$return = false;
}
else 
{
return true;
}


// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		
$sql = DB::prepareSQL("UPDATE
sep2.000_global
LEFT JOIN sep2.q_ctrl_saldo_000 ON sep2.000_global.RUBRO_ID = sep2.q_ctrl_saldo_000.RUBRO_ID_FK
SET
sep2.000_global.SALDO = IF(sep2.q_ctrl_saldo_000.UTILIZADO IS NULL, sep2.000_global.PRESUPUESTO,(sep2.000_global.PRESUPUESTO-sep2.q_ctrl_saldo_000.UTILIZADO));");
DB::Exec( $sql );


$sql = DB::prepareSQL("UPDATE
sep2.000_global
LEFT JOIN sep2.q_ctrl_saldo_000 ON sep2.000_global.RUBRO_ID = sep2.q_ctrl_saldo_000.RUBRO_ID_FK
SET
sep2.000_global.UTILIZADO = IF(sep2.q_ctrl_saldo_000.UTILIZADO IS NULL,(sep2.000_global.PRESUPUESTO-sep2.000_global.SALDO),sep2.q_ctrl_saldo_000.UTILIZADO);");
DB::Exec( $sql );








// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record deleted
function AfterDelete($where, &$deleted_values, &$message, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
sep2.000_global
LEFT JOIN sep2.q_ctrl_saldo_000 ON sep2.000_global.RUBRO_ID = sep2.q_ctrl_saldo_000.RUBRO_ID_FK
SET
sep2.000_global.SALDO = IF(sep2.q_ctrl_saldo_000.UTILIZADO IS NULL, sep2.000_global.PRESUPUESTO,(sep2.000_global.PRESUPUESTO-sep2.q_ctrl_saldo_000.UTILIZADO));");
DB::Exec( $sql );


$sql = DB::prepareSQL("UPDATE
sep2.000_global
LEFT JOIN sep2.q_ctrl_saldo_000 ON sep2.000_global.RUBRO_ID = sep2.q_ctrl_saldo_000.RUBRO_ID_FK
SET
sep2.000_global.UTILIZADO = IF(sep2.q_ctrl_saldo_000.UTILIZADO IS NULL,(sep2.000_global.PRESUPUESTO-sep2.000_global.SALDO),sep2.q_ctrl_saldo_000.UTILIZADO);");
DB::Exec( $sql );
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
