<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_002_producto  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterDelete"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record deleted
function AfterDelete($where, &$deleted_values, &$message, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
sep2.001_rubro
INNER JOIN sep2.q_ctrl_saldo_001 ON sep2.001_rubro.VIGENCIA = sep2.q_ctrl_saldo_001.VIGENCIA AND sep2.001_rubro.UEJ = sep2.q_ctrl_saldo_001.UEJ AND sep2.001_rubro.RUBRO = sep2.q_ctrl_saldo_001.RUBRO AND sep2.001_rubro.REC = sep2.q_ctrl_saldo_001.REC
SET
sep2.001_rubro.SALDO = (sep2.001_rubro.PRESUPUESTO -sep2.q_ctrl_saldo_001.UTILIZADO);");
DB::Exec( $sql );



// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
sep2.001_rubro
INNER JOIN sep2.q_ctrl_saldo_001 ON sep2.001_rubro.VIGENCIA = sep2.q_ctrl_saldo_001.VIGENCIA AND sep2.001_rubro.UEJ = sep2.q_ctrl_saldo_001.UEJ AND sep2.001_rubro.RUBRO = sep2.q_ctrl_saldo_001.RUBRO AND sep2.001_rubro.REC = sep2.q_ctrl_saldo_001.REC
SET
sep2.001_rubro.SALDO = (sep2.001_rubro.PRESUPUESTO -sep2.q_ctrl_saldo_001.UTILIZADO);");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
sep2.001_rubro
INNER JOIN sep2.q_ctrl_saldo_001 ON sep2.001_rubro.VIGENCIA = sep2.q_ctrl_saldo_001.VIGENCIA AND sep2.001_rubro.UEJ = sep2.q_ctrl_saldo_001.UEJ AND sep2.001_rubro.RUBRO = sep2.q_ctrl_saldo_001.RUBRO AND sep2.001_rubro.REC = sep2.q_ctrl_saldo_001.REC
SET
sep2.001_rubro.SALDO = (sep2.001_rubro.PRESUPUESTO -sep2.q_ctrl_saldo_001.UTILIZADO);");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
