<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_003_actividad  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterDelete"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;

		$this->events["GetTablePermissions"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record deleted
function AfterDelete($where, &$deleted_values, &$message, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
sep2.002_producto
INNER JOIN sep2.q_ctrl_saldo_002 ON sep2.002_producto.PROD_ID = sep2.q_ctrl_saldo_002.PROD_ID_FK
SET
sep2.002_producto.SALDO = (sep2.002_producto.PROD_PRESUPUESTO - sep2.q_ctrl_saldo_002.UTILIZADO);");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
sep2.002_producto
INNER JOIN sep2.q_ctrl_saldo_002 ON sep2.002_producto.PROD_ID = sep2.q_ctrl_saldo_002.PROD_ID_FK
SET
sep2.002_producto.SALDO = (sep2.002_producto.PROD_PRESUPUESTO - sep2.q_ctrl_saldo_002.UTILIZADO);");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
sep2.002_producto
INNER JOIN sep2.q_ctrl_saldo_002 ON sep2.002_producto.PROD_ID = sep2.q_ctrl_saldo_002.PROD_ID_FK
SET
sep2.002_producto.SALDO = (sep2.002_producto.PROD_PRESUPUESTO - sep2.q_ctrl_saldo_002.UTILIZADO);");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Get Table Permissions
function GetTablePermissions($permissions)
{

		if ($_SESSION['actividad_add'] == TRUE ) {
		$permissions = str_replace("A", "", $permissions); // Quita  "A"
		//$permissions = str_replace("D", "", $permissions); // Quita  "D"
		//$permissions = str_replace("E", "", $permissions); // Quita  "E"
}

// Place event code here.
// Use "Add Action" button to add code snippets.

return $permissions;
;		
} // function GetTablePermissions

		
		
		
		
		
		
		
		



}
?>
